### ISSUE TITLE
List of all issues GBIF provides

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#26]
* [x] `BASIS_OF_RECORD_INVALID` ignored in #28
* [ ] `CONTINENT_COUNTRY_MISMATCH`
* [ ] `CONTINENT_DERIVED_FROM_COORDINATES`
* [ ] `CONTINENT_INVALID`
* [x] `COORDINATE_INVALID` major in #23
* [x] `COORDINATE_OUT_OF_RANGE` #23
* [x] `COORDINATE_REPROJECTED` ignored in #23
* [x] `COORDINATE_REPROJECTION_FAILED` minor in #23
* [x] `COORDINATE_REPROJECTION_SUSPICIOUS` minor in #23
* [x] `COORDINATE_ROUNDED` ignored in  #23
* [x] `COUNTRY_COORDINATE_MISMATCH`  major in #23
* [ ] `COUNTRY_DERIVED_FROM_COORDINATES`
* [ ] `COUNTRY_INVALID`
* [ ] `COUNTRY_MISMATCH`
* [ ] `DEPTH_MIN_MAX_SWAPPED`
* [ ] `DEPTH_NON_NUMERIC`
* [ ] `DEPTH_NOT_METRIC`
* [ ] `DEPTH_UNLIKELY`
* [ ] `ELEVATION_MIN_MAC_SWAPPED`
* [ ] `ELEVATION_NON_NUMERIC`
* [ ] `ELEVATION_NOT_METRIC`
* [ ] `ELEVATION_UNLIKELY`
* [x] `GEODETIC_DATUM_ASSUMED_WGS84` ignored in  #23
* [x] `GEODETIC_DATUM_INVALID` minor in #23
* [ ] `IDENTIFIED_DATE_INVALID`
* [ ] `IDENTIFIED_DATE_UNLIKELY`
* [ ] `MODIFIED_DATE_INVALID`
* [ ] `MODIFIED_DATE_UNLIKELY`
* [x] `MULTIMEDIA_DATE_INVALID` ignored in #43
* [x] `MULTIMEDIA_URI_INVALID` used in #43
* [x] `PRESUMED_NEGATED_LATITUDE` ignored in #23
* [x] `PRESUMED_NEGATED_LONGITUDE` ignored in #23
* [x] `PRESUMED_SWAPPED_COORDINATE` ignored in #23
* [ ] `RECORDED_DATE_INVALID`
* [ ] `RECORDED_DATE_MISMATCH`
* [ ] `RECORDED_DATE_UNLIKELY`
* [ ] `REFERENCES_URI_INVALID`
* [x] `TAXON_MATCH_FUZZY` used in #39
* [x] `TAXON_MATCH_HIGHER_RANK` used in #39
* [x] `TAXON_MATCH_NONE` used in #39
* [ ] `TYPE_STATUS_INVALID`
* [x] `ZERO_COORDINATE` major in #23

**Comment by peterdesmet** [comment]
This is documentation, not a task. Closing.
